language: ruby
rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.sample config/database.yml
  - mysql -e "create database courses_test;"

script:
  - RAILS_ENV=test bundle exec rake db:test:load --trace
  - bundle exec rake
