language: ruby
rvm:
  - 2.0.0

bundler_args: "--without development production"  
before_script:
  - cp config/database.yml.sample config/database.yml
  - mysql -e "create database courses_test;"

script:
  - RAILS_ENV=test bundle exec rake db:test:load --trace
  - bundle exec rake

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/49ce887600e6dbfb7553
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
